# Generated by Django 5.0.1 on 2024-05-11 10:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0004_order_address_order_delivery_time'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='delivery_time',
        ),
    ]
